import { IPeople } from '../SWApi';

export const testResponseSinglePerson = {
  name: 'Luke Skywalker',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male+',
  homeworld: 'https://swapi.dev/api/planets/1/',
  films: [
    'https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/6/',
  ],
  species: [],
  vehicles: [
    'https://swapi.dev/api/vehicles/14/',
    'https://swapi.dev/api/vehicles/30/',
  ],
  starships: [
    'https://swapi.dev/api/starships/12/',
    'https://swapi.dev/api/starships/22/',
  ],
  created: '2014-12-09T13:50:51.644000Z',
  edited: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.dev/api/people/1/',
};

export const testSinglePerson: IPeople = {
  name: 'Luke Skywalker',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.dev/api/planets/1/',
  films: [
    'https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/6/',
  ],
  species: [],
  vehicles: [
    'https://swapi.dev/api/vehicles/14/',
    'https://swapi.dev/api/vehicles/30/',
  ],
  starships: [
    'https://swapi.dev/api/starships/12/',
    'https://swapi.dev/api/starships/22/',
  ],
  created: new Date('2014-12-09T13:50:51.644000Z'),
  edited: new Date('2014-12-20T21:17:56.891000Z'),
  url: 'https://swapi.dev/api/people/1/',
};

export const testSinglePerson2: IPeople = {
  name: 'Leia Organa',
  height: '150',
  mass: '49',
  hair_color: 'brown',
  skin_color: 'light',
  eye_color: 'brown',
  birth_year: '19BBY',
  gender: 'female',
  homeworld: 'https://swapi.dev/api/planets/2/',
  films: [
    'https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/6/',
  ],
  species: [],
  vehicles: ['https://swapi.dev/api/vehicles/30/'],
  starships: [],
  created: new Date('2014-12-10T15:20:09.791000Z'),
  edited: new Date('2014-12-20T21:17:50.315000Z'),
  url: 'https://swapi.dev/api/people/5/',
};

export const testPeopleArray2: IPeople[] = [
  {
    name: 'Luke Skywalker',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/1/',
    films: [
      'https://swapi.dev/api/films/1/',
      'https://swapi.dev/api/films/2/',
      'https://swapi.dev/api/films/3/',
      'https://swapi.dev/api/films/6/',
    ],
    species: [],
    vehicles: [
      'https://swapi.dev/api/vehicles/14/',
      'https://swapi.dev/api/vehicles/30/',
    ],
    starships: [
      'https://swapi.dev/api/starships/12/',
      'https://swapi.dev/api/starships/22/',
    ],
    created: new Date('2014-12-09T13:50:51.644000Z'),
    edited: new Date('2014-12-20T21:17:56.891000Z'),
    url: 'https://swapi.dev/api/people/1/',
  },
  {
    name: 'Leia Organa',
    height: '150',
    mass: '49',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '19BBY',
    gender: 'female',
    homeworld: 'https://swapi.dev/api/planets/2/',
    films: [
      'https://swapi.dev/api/films/1/',
      'https://swapi.dev/api/films/2/',
      'https://swapi.dev/api/films/3/',
      'https://swapi.dev/api/films/6/',
    ],
    species: [],
    vehicles: ['https://swapi.dev/api/vehicles/30/'],
    starships: [],
    created: new Date('2014-12-10T15:20:09.791000Z'),
    edited: new Date('2014-12-20T21:17:50.315000Z'),
    url: 'https://swapi.dev/api/people/5/',
  },
];

export const testResponsePeople2 = {
  count: 2,
  next: null,
  previous: null,
  results: [
    {
      name: 'Luke Skywalker',
      height: '172',
      mass: '77',
      hair_color: 'blond',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '19BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/6/',
      ],
      species: [],
      vehicles: [
        'https://swapi.dev/api/vehicles/14/',
        'https://swapi.dev/api/vehicles/30/',
      ],
      starships: [
        'https://swapi.dev/api/starships/12/',
        'https://swapi.dev/api/starships/22/',
      ],
      created: '2014-12-09T13:50:51.644000Z',
      edited: '2014-12-20T21:17:56.891000Z',
      url: 'https://swapi.dev/api/people/1/',
    },
    {
      name: 'Luminara Unduli',
      height: '170',
      mass: '56.2',
      hair_color: 'black',
      skin_color: 'yellow',
      eye_color: 'blue',
      birth_year: '58BBY',
      gender: 'female',
      homeworld: 'https://swapi.dev/api/planets/51/',
      films: [
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: ['https://swapi.dev/api/species/29/'],
      vehicles: [],
      starships: [],
      created: '2014-12-20T16:45:53.668000Z',
      edited: '2014-12-20T21:17:50.455000Z',
      url: 'https://swapi.dev/api/people/64/',
    },
  ],
};

export const testResponsePeople18p1 = {
  count: 18,
  next: 'https://swapi.dev/api/people/?search=k&page=2',
  previous: null,
  results: [
    {
      name: 'Luke Skywalker',
      height: '172',
      mass: '77',
      hair_color: 'blond',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '19BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/6/',
      ],
      species: [],
      vehicles: [
        'https://swapi.dev/api/vehicles/14/',
        'https://swapi.dev/api/vehicles/30/',
      ],
      starships: [
        'https://swapi.dev/api/starships/12/',
        'https://swapi.dev/api/starships/22/',
      ],
      created: '2014-12-09T13:50:51.644000Z',
      edited: '2014-12-20T21:17:56.891000Z',
      url: 'https://swapi.dev/api/people/1/',
    },
    {
      name: 'Biggs Darklighter',
      height: '183',
      mass: '84',
      hair_color: 'black',
      skin_color: 'light',
      eye_color: 'brown',
      birth_year: '24BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: ['https://swapi.dev/api/films/1/'],
      species: [],
      vehicles: [],
      starships: ['https://swapi.dev/api/starships/12/'],
      created: '2014-12-10T15:59:50.509000Z',
      edited: '2014-12-20T21:17:50.323000Z',
      url: 'https://swapi.dev/api/people/9/',
    },
    {
      name: 'Obi-Wan Kenobi',
      height: '182',
      mass: '77',
      hair_color: 'auburn, white',
      skin_color: 'fair',
      eye_color: 'blue-gray',
      birth_year: '57BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/20/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: [],
      vehicles: ['https://swapi.dev/api/vehicles/38/'],
      starships: [
        'https://swapi.dev/api/starships/48/',
        'https://swapi.dev/api/starships/59/',
        'https://swapi.dev/api/starships/64/',
        'https://swapi.dev/api/starships/65/',
        'https://swapi.dev/api/starships/74/',
      ],
      created: '2014-12-10T16:16:29.192000Z',
      edited: '2014-12-20T21:17:50.325000Z',
      url: 'https://swapi.dev/api/people/10/',
    },
    {
      name: 'Anakin Skywalker',
      height: '188',
      mass: '84',
      hair_color: 'blond',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '41.9BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: [
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: [],
      vehicles: [
        'https://swapi.dev/api/vehicles/44/',
        'https://swapi.dev/api/vehicles/46/',
      ],
      starships: [
        'https://swapi.dev/api/starships/39/',
        'https://swapi.dev/api/starships/59/',
        'https://swapi.dev/api/starships/65/',
      ],
      created: '2014-12-10T16:20:44.310000Z',
      edited: '2014-12-20T21:17:50.327000Z',
      url: 'https://swapi.dev/api/people/11/',
    },
    {
      name: 'Wilhuff Tarkin',
      height: '180',
      mass: 'unknown',
      hair_color: 'auburn, grey',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '64BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/21/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/6/',
      ],
      species: [],
      vehicles: [],
      starships: [],
      created: '2014-12-10T16:26:56.138000Z',
      edited: '2014-12-20T21:17:50.330000Z',
      url: 'https://swapi.dev/api/people/12/',
    },
    {
      name: 'Jek Tono Porkins',
      height: '180',
      mass: '110',
      hair_color: 'brown',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/26/',
      films: ['https://swapi.dev/api/films/1/'],
      species: [],
      vehicles: [],
      starships: ['https://swapi.dev/api/starships/12/'],
      created: '2014-12-12T11:16:56.569000Z',
      edited: '2014-12-20T21:17:50.343000Z',
      url: 'https://swapi.dev/api/people/19/',
    },
    {
      name: 'Bossk',
      height: '190',
      mass: '113',
      hair_color: 'none',
      skin_color: 'green',
      eye_color: 'red',
      birth_year: '53BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/29/',
      films: ['https://swapi.dev/api/films/2/'],
      species: ['https://swapi.dev/api/species/7/'],
      vehicles: [],
      starships: [],
      created: '2014-12-15T12:53:49.297000Z',
      edited: '2014-12-20T21:17:50.355000Z',
      url: 'https://swapi.dev/api/people/24/',
    },
    {
      name: 'Ackbar',
      height: '180',
      mass: '83',
      hair_color: 'none',
      skin_color: 'brown mottle',
      eye_color: 'orange',
      birth_year: '41BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/31/',
      films: ['https://swapi.dev/api/films/3/'],
      species: ['https://swapi.dev/api/species/8/'],
      vehicles: [],
      starships: [],
      created: '2014-12-18T11:07:50.584000Z',
      edited: '2014-12-20T21:17:50.362000Z',
      url: 'https://swapi.dev/api/people/27/',
    },
    {
      name: 'Wicket Systri Warrick',
      height: '88',
      mass: '20',
      hair_color: 'brown',
      skin_color: 'brown',
      eye_color: 'brown',
      birth_year: '8BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/7/',
      films: ['https://swapi.dev/api/films/3/'],
      species: ['https://swapi.dev/api/species/9/'],
      vehicles: [],
      starships: [],
      created: '2014-12-18T11:21:58.954000Z',
      edited: '2014-12-20T21:17:50.369000Z',
      url: 'https://swapi.dev/api/people/30/',
    },
    {
      name: 'Jar Jar Binks',
      height: '196',
      mass: '66',
      hair_color: 'none',
      skin_color: 'orange',
      eye_color: 'orange',
      birth_year: '52BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/8/',
      films: [
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
      ],
      species: ['https://swapi.dev/api/species/12/'],
      vehicles: [],
      starships: [],
      created: '2014-12-19T17:29:32.489000Z',
      edited: '2014-12-20T21:17:50.383000Z',
      url: 'https://swapi.dev/api/people/36/',
    },
  ],
};

export const testResponsePeople18p2 = {
  count: 18,
  next: null,
  previous: 'https://swapi.dev/api/people/?search=k&page=1',
  results: [
    {
      name: 'Quarsh Panaka',
      height: '183',
      mass: 'unknown',
      hair_color: 'black',
      skin_color: 'dark',
      eye_color: 'brown',
      birth_year: '62BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/8/',
      films: ['https://swapi.dev/api/films/4/'],
      species: [],
      vehicles: [],
      starships: [],
      created: '2014-12-19T17:55:43.348000Z',
      edited: '2014-12-20T21:17:50.399000Z',
      url: 'https://swapi.dev/api/people/42/',
    },
    {
      name: 'Shmi Skywalker',
      height: '163',
      mass: 'unknown',
      hair_color: 'black',
      skin_color: 'fair',
      eye_color: 'brown',
      birth_year: '72BBY',
      gender: 'female',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: [
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
      ],
      species: [],
      vehicles: [],
      starships: [],
      created: '2014-12-19T17:57:41.191000Z',
      edited: '2014-12-20T21:17:50.401000Z',
      url: 'https://swapi.dev/api/people/43/',
    },
    {
      name: 'Ki-Adi-Mundi',
      height: '198',
      mass: '82',
      hair_color: 'white',
      skin_color: 'pale',
      eye_color: 'yellow',
      birth_year: '92BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/43/',
      films: [
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: ['https://swapi.dev/api/species/20/'],
      vehicles: [],
      starships: [],
      created: '2014-12-20T10:15:32.293000Z',
      edited: '2014-12-20T21:17:50.422000Z',
      url: 'https://swapi.dev/api/people/52/',
    },
    {
      name: 'Kit Fisto',
      height: '196',
      mass: '87',
      hair_color: 'none',
      skin_color: 'green',
      eye_color: 'black',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/44/',
      films: [
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: ['https://swapi.dev/api/species/21/'],
      vehicles: [],
      starships: [],
      created: '2014-12-20T10:18:57.202000Z',
      edited: '2014-12-20T21:17:50.424000Z',
      url: 'https://swapi.dev/api/people/53/',
    },
    {
      name: 'Eeth Koth',
      height: '171',
      mass: 'unknown',
      hair_color: 'black',
      skin_color: 'brown',
      eye_color: 'brown',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/45/',
      films: [
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/6/',
      ],
      species: ['https://swapi.dev/api/species/22/'],
      vehicles: [],
      starships: [],
      created: '2014-12-20T10:26:47.902000Z',
      edited: '2014-12-20T21:17:50.427000Z',
      url: 'https://swapi.dev/api/people/54/',
    },
    {
      name: 'Plo Koon',
      height: '188',
      mass: '80',
      hair_color: 'none',
      skin_color: 'orange',
      eye_color: 'black',
      birth_year: '22BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/49/',
      films: [
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: ['https://swapi.dev/api/species/26/'],
      vehicles: [],
      starships: ['https://swapi.dev/api/starships/48/'],
      created: '2014-12-20T10:49:19.859000Z',
      edited: '2014-12-20T21:17:50.439000Z',
      url: 'https://swapi.dev/api/people/58/',
    },
    {
      name: 'Dooku',
      height: '193',
      mass: '80',
      hair_color: 'white',
      skin_color: 'fair',
      eye_color: 'brown',
      birth_year: '102BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/52/',
      films: [
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: ['https://swapi.dev/api/species/1/'],
      vehicles: ['https://swapi.dev/api/vehicles/55/'],
      starships: [],
      created: '2014-12-20T16:52:14.726000Z',
      edited: '2014-12-20T21:17:50.462000Z',
      url: 'https://swapi.dev/api/people/67/',
    },
    {
      name: 'Shaak Ti',
      height: '178',
      mass: '57',
      hair_color: 'none',
      skin_color: 'red, blue, white',
      eye_color: 'black',
      birth_year: 'unknown',
      gender: 'female',
      homeworld: 'https://swapi.dev/api/planets/58/',
      films: [
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: ['https://swapi.dev/api/species/35/'],
      vehicles: [],
      starships: [],
      created: '2014-12-20T18:44:01.103000Z',
      edited: '2014-12-20T21:17:50.486000Z',
      url: 'https://swapi.dev/api/people/78/',
    },
  ],
};
